package com.arlania.world.content.perk_system;

public enum PerkType {
	TEN_PERCENT_MORE_BLOODBAGS,
	TWENTY_FIVE_PERCENT_MORE_BLOODBAGS,
	TEN_PERCENT_MORE_BLOOD_SLAYER_POINTS,
	TWENTY_FIVE_PERCENT_MORE_BLOOD_SLAYER_POINTS,
	FIFTY_PERCENT_MORE_BLOOD_SLAYER_POINTS,
	FIVE_PERCENT_MORE_DROP_RATE,
	TEN_PERCENT_MORE_DROP_RATE,
	FIFTEEN_PERCENT_DOUBLE_DROPS,
	TWENTY_FIVE_PERCENTY_DOUBLE_DROPS,
	ZERO_PT_TEN_DAMAGE_BOOST,
	ZERO_PT_TWENTY_FIVE_DAMAGE_BOOST;
}
